---
stages:
- name: Globalize
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  properties:
  - name: THIS_SUBMISSION_NAME
    value: com.ibm.translation
    type: text
  jobs:
  - name: machine translation
    type: builder
    extension_id: ibm.devops.services.pipeline.globalization.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    SETUP_SERVICE_SPACE: 'true'
    INPUT_PATTERN: translation_en.properties
